apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker/docker-compose.yml --controller deployment
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker/docker-compose.yml --controller deployment
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-nextcloud-net: "true"
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_HOST
              value: db
            - name: MYSQL_PASSWORD
              value: mysqlpass
            - name: MYSQL_USER
              value: nextcloud
          image: nextcloud
          name: app
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
           #- mountPath: /toto
           #  name: volume
           # - mountPath: ~/lapmn-kubernetes-tps/tp3-4bis/config/config-mapssh.txt
           #   name: cm-ssh
      restartPolicy: Always
      volumes:
        - name: demo-volume
          nfs:
            server: 192.168.254.254
            path: /var/lib/nfsdata
            readOnly: false  
      # - name: nextcloud-data
      #   persistentVolumeClaim:
      #     claimName: nextcloud-data
status: {}

